/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacote;

import conn.Conexao;
import static conn.Conexao.Conectar;
import static conn.Conexao.con;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.net.ftp.FTPClient;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class tFTP extends javax.swing.JFrame {
    DefaultListModel listaCaminho = new DefaultListModel();
    DefaultListModel listaNome = new DefaultListModel();
    /**
     * Creates new form tFTP
     */
    
    public String idImovel = "";
    
    public String getId() {
        return idImovel;
    }
    
    public void setId(String idImovel){
        this.idImovel = idImovel;
    }       
    
    public tFTP() {
        initComponents();
    }
    
    public tFTP(String idImovelRecebido){
        this.idImovel = idImovelRecebido;
        initComponents();
        Conectar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FC = new javax.swing.JFileChooser();
        tfNomeArq = new javax.swing.JTextField();
        tfCaminho = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNome = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCaminho = new javax.swing.JList<>();
        btAdd = new javax.swing.JButton();
        btEnviar = new javax.swing.JButton();
        btProcurar = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstNome);

        jScrollPane2.setViewportView(lstCaminho);

        btAdd.setText("Adicionar");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEnviar.setText("FTP");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        btProcurar.setText("Procurar");
        btProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfNomeArq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                        .addComponent(tfCaminho, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btAdd))
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProcurar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btEnviar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(btEnviar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNomeArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(btProcurar)
                        .addGap(18, 18, 18)
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btAdd)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarActionPerformed
        //Aqui começa a rotina de selecionar os arquivos usando o fileChoser
        File arquivo;
        String nomeArq;
        BufferedImage imagem;
        FC.setFileFilter(new FileNameExtensionFilter("Image files", "png", "jpg"));
        FC.setAcceptAllFileFilterUsed(false);
        FC.showOpenDialog(null);
        arquivo = FC.getSelectedFile();
        nomeArq = FC.getName(arquivo);
        tfNomeArq.setText(nomeArq);
        tfCaminho.setText(arquivo.toString());
        
        try{
            imagem = ImageIO.read(arquivo);
            ImageIcon icon = new ImageIcon(imagem.getScaledInstance(400, 400, java.awt.Image.SCALE_SMOOTH));
            lb1.setIcon(icon);
            
            
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Erro!" +e);
        }
    }//GEN-LAST:event_btProcurarActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed

        //Define o modelo das lista e passa os dados a elas;
        lstCaminho.setModel(listaCaminho);
        lstNome.setModel(listaNome);
        listaCaminho.addElement(tfCaminho.getText());
        listaNome.addElement(tfNomeArq.getText());
    }//GEN-LAST:event_btAddActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        int tam;
        tam = lstNome.getModel().getSize()-1;
        //Rotina de inclusão de imagens no B.D
        try{
            for(int i = 0; i<=tam; i++){
                String sql = "insert into imagens(id_imovel, imagem) values (" +  idImovel + ",'" + idImovel+"_"+listaNome.getElementAt(i).toString()+"')";
                PreparedStatement stm = con.prepareStatement(sql);
                stm.executeUpdate();
            }
            
        } catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Erro ao incluir as imagens! " +erro);
        }
        //Rotina para guardar o arquivo de imagem em um servidor
        try{
            FTPClient ftp = new FTPClient();
            ftp.connect("127.0.0.1");
            ftp.login("Vitor","1007");
            ftp.setFileType(FTPClient.BINARY_FILE_TYPE);
            
            ftp.makeDirectory(idImovel);
            ftp.changeWorkingDirectory(idImovel);
            
            for(int i = 0; i<=tam; i++){
                FileInputStream arqEnviar = new FileInputStream(listaCaminho.getElementAt(i).toString());
                if(ftp.storeFile(idImovel+"_"+listaNome.getElementAt(i),arqEnviar)){
                    JOptionPane.showMessageDialog(null, "Arquivo armazenado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao aramazenar o arquivo!");
                }
            }
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Erro! " + e);
        }
    }//GEN-LAST:event_btEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tFTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tFTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tFTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tFTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tFTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FC;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btProcurar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb1;
    private javax.swing.JList<String> lstCaminho;
    private javax.swing.JList<String> lstNome;
    private javax.swing.JTextField tfCaminho;
    private javax.swing.JTextField tfNomeArq;
    // End of variables declaration//GEN-END:variables
}
