/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacote;

import static conn.Conexao.Conectar;
import static conn.Conexao.Desconectar;
import static conn.Conexao.con;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class tPesquisa extends javax.swing.JFrame {
    DefaultTableModel imoveis;
    /**
     * Creates new form tPesquisa
     */
    
    public void limparTabela(){
        imoveis.setRowCount(0);
    }
    
    public void limparCampos(){
        tfDadoPesquisa.setText("");
        tfTitulo.setText("");
        taDesc.setText("");
        tfMetragem.setText("");
        tfValor.setText("");
        tfIptu.setText("");
        tfBairro.setText("");
        tfEndereco.setText("");
        spBanheiros.setValue(1);
        spSuites.setValue(1);
        spQuartos.setValue(1);
        cbTp_Negocio.setSelectedIndex(0);
        tfCidade.setText("");
        tfTipoImovel.setText("");
        tfTipoNegocio.setText("");
    }
    
    public tPesquisa() {
        initComponents();
        Conectar();
        pTabela.setVisible(false);
        tfID.setVisible(false);
        imoveis = (DefaultTableModel) jTable1.getModel();
        limparTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();
        btSairTabela = new javax.swing.JButton();
        pAlterar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbCidade = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDesc = new javax.swing.JTextArea();
        tfBairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfMetragem = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spSuites = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spQuartos = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spBanheiros = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        cbTp_imov = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbTp_Negocio = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfIptu = new javax.swing.JTextField();
        tfTitulo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        tfCidade = new javax.swing.JTextField();
        tfTipoImovel = new javax.swing.JTextField();
        tfTipoNegocio = new javax.swing.JTextField();
        btLimpa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfDadoPesquisa = new javax.swing.JTextField();
        btPesquisa = new javax.swing.JButton();
        tfID = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 950));
        getContentPane().setLayout(null);

        pTabela.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pTabela.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pTabela.add(jScrollPane1);
        jScrollPane1.setBounds(8, 45, 573, 233);

        btSelecionar.setText("Selecionar");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });
        pTabela.add(btSelecionar);
        btSelecionar.setBounds(497, 284, 84, 23);

        btSairTabela.setBackground(new java.awt.Color(255, 51, 51));
        btSairTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSairTabela.setForeground(new java.awt.Color(242, 242, 242));
        btSairTabela.setText("X");
        btSairTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairTabelaActionPerformed(evt);
            }
        });
        pTabela.add(btSairTabela);
        btSairTabela.setBounds(532, 8, 49, 23);

        getContentPane().add(pTabela);
        pTabela.setBounds(380, 70, 600, 320);

        pAlterar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pAlterar.setMinimumSize(new java.awt.Dimension(700, 520));
        pAlterar.setPreferredSize(new java.awt.Dimension(800, 620));

        jLabel3.setText("Descrição");

        cbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP\tAdamantina", "SP\tAdolfo", "SP\tAguaí", "SP\tÁguas da Prata", "SP\tÁguas de Lindóia", "SP\tÁguas de Santa Bárbara", "SP\tÁguas de São Pedro", "SP\tAgudos", "SP\tAlambari", "SP\tAlfredo Marcondes", "SP\tAltair", "SP\tAltinópolis", "SP\tAlto Alegre", "SP\tAlumínio", "SP\tÁlvares Florence", "SP\tÁlvares Machado", "SP\tÁlvaro de Carvalho", "SP\tAlvinlândia", "SP\tAmericana", "SP\tAmérico Brasiliense", "SP\tAmérico de Campos", "SP\tAmparo", "SP\tAnalândia", "SP\tAndradina", "SP\tAngatuba", "SP\tAnhembi", "SP\tAnhumas", "SP\tAparecida", "SP\tAparecida D´oeste", "SP\tApiaí", "SP\tAraçariguama", "SP\tAraçatuba", "SP\tAraçoiaba da Serra", "SP\tAramina", "SP\tArandu", "SP\tArapeí", "SP\tAraraquara", "SP\tAraras", "SP\tArco-íris", "SP\tArealva", "SP\tAreias", "SP\tAreiópolis", "SP\tAriranha", "SP\tArtur Nogueira", "SP\tArujá", "SP\tAspásia", "SP\tAssis", "SP\tAtibaia", "SP\tAuriflama", "SP\tAvaí", "SP\tAvanhandava", "SP\tAvaré", "SP\tBady Bassitt", "SP\tBalbinos", "SP\tBálsamo", "SP\tBananal", "SP\tBarão de Antonina", "SP\tBarbosa", "SP\tBariri", "SP\tBarra Bonita", "SP\tBarra do Chapéu", "SP\tBarra do Turvo", "SP\tBarretos", "SP\tBarrinha", "SP\tBarueri", "SP\tBastos", "SP\tBatatais", "SP\tBauru", "SP\tBebedouro", "SP\tBento de Abreu", "SP\tBernardino de Campos", "SP\tBertioga", "SP\tBilac", "SP\tBirigui", "SP\tBiritiba-mirim", "SP\tBoa Esperança do Sul", "SP\tBocaina", "SP\tBofete", "SP\tBoituva", "SP\tBom Jesus Dos Perdões", "SP\tBom Sucesso de Itararé", "SP\tBorá", "SP\tBoracéia", "SP\tBorborema", "SP\tBorebi", "SP\tBotucatu", "SP\tBragança Paulista", "SP\tBraúna", "SP\tBrejo Alegre", "SP\tBrodowski", "SP\tBrotas", "SP\tBuri", "SP\tBuritama", "SP\tBuritizal", "SP\tCabrália Paulista", "SP\tCabreúva", "SP\tCaçapava", "SP\tCachoeira Paulista", "SP\tCaconde", "SP\tCafelândia", "SP\tCaiabu", "SP\tCaieiras", "SP\tCaiuá", "SP\tCajamar", "SP\tCajati", "SP\tCajobi", "SP\tCajuru", "SP\tCampina do Monte Alegre", "SP\tCampinas", "SP\tCampo Limpo Paulista", "SP\tCampos do Jordão", "SP\tCampos Novos Paulista", "SP\tCananéia", "SP\tCanas", "SP\tCândido Mota", "SP\tCândido Rodrigues", "SP\tCanitar", "SP\tCapão Bonito", "SP\tCapela do Alto", "SP\tCapivari", "SP\tCaraguatatuba", "SP\tCarapicuíba", "SP\tCardoso", "SP\tCasa Branca", "SP\tCássia Dos Coqueiros", "SP\tCastilho", "SP\tCatanduva", "SP\tCatiguá", "SP\tCedral", "SP\tCerqueira César", "SP\tCerquilho", "SP\tCesário Lange", "SP\tCharqueada", "SP\tClementina", "SP\tColina", "SP\tColômbia", "SP\tConchal", "SP\tConchas", "SP\tCordeirópolis", "SP\tCoroados", "SP\tCoronel Macedo", "SP\tCorumbataí", "SP\tCosmópolis", "SP\tCosmorama", "SP\tCotia", "SP\tCravinhos", "SP\tCristais Paulista", "SP\tCruzália", "SP\tCruzeiro", "SP\tCubatão", "SP\tCunha", "SP\tDescalvado", "SP\tDiadema", "SP\tDirce Reis", "SP\tDivinolândia", "SP\tDobrada", "SP\tDois Córregos", "SP\tDolcinópolis", "SP\tDourado", "SP\tDracena", "SP\tDuartina", "SP\tDumont", "SP\tEchaporã", "SP\tEldorado", "SP\tElias Fausto", "SP\tElisiário", "SP\tEmbaúba", "SP\tEmbu", "SP\tEmbu-guaçu", "SP\tEmilianópolis", "SP\tEngenheiro Coelho", "SP\tEspírito Santo do Pinhal", "SP\tEspírito Santo do Turvo", "SP\tEstrela D´oeste", "SP\tEstrela do Norte", "SP\tEuclides da Cunha Paulista", "SP\tFartura", "SP\tFernandópolis", "SP\tFernando Prestes", "SP\tFernão", "SP\tFerraz de Vasconcelos", "SP\tFlora Rica", "SP\tFloreal", "SP\tFlórida Paulista", "SP\tFlorínia", "SP\tFranca", "SP\tFrancisco Morato", "SP\tFranco da Rocha", "SP\tGabriel Monteiro", "SP\tGália", "SP\tGarça", "SP\tGastão Vidigal", "SP\tGavião Peixoto", "SP\tGeneral Salgado", "SP\tGetulina", "SP\tGlicério", "SP\tGuaiçara", "SP\tGuaimbê", "SP\tGuaíra", "SP\tGuapiaçu", "SP\tGuapiara", "SP\tGuará", "SP\tGuaraçaí", "SP\tGuaraci", "SP\tGuarani D´oeste", "SP\tGuarantã", "SP\tGuararapes", "SP\tGuararema", "SP\tGuaratinguetá", "SP\tGuareí", "SP\tGuariba", "SP\tGuarujá", "SP\tGuarulhos", "SP\tGuatapará", "SP\tGuzolândia", "SP\tHerculândia", "SP\tHolambra", "SP\tHortolândia", "SP\tIacanga", "SP\tIacri", "SP\tIaras", "SP\tIbaté", "SP\tIbirá", "SP\tIbirarema", "SP\tIbitinga", "SP\tIbiúna", "SP\tIcém", "SP\tIepê", "SP\tIgaraçu do Tietê", "SP\tIgarapava", "SP\tIgaratá", "SP\tIguape", "SP\tIlhabela", "SP\tIlha Comprida", "SP\tIlha Solteira", "SP\tIndaiatuba", "SP\tIndiana", "SP\tIndiaporã", "SP\tInúbia Paulista", "SP\tIpaussu", "SP\tIperó", "SP\tIpeúna", "SP\tIpiguá", "SP\tIporanga", "SP\tIpuã", "SP\tIracemápolis", "SP\tIrapuã", "SP\tIrapuru", "SP\tItaberá", "SP\tItaí", "SP\tItajobi", "SP\tItaju", "SP\tItanhaém", "SP\tItaóca", "SP\tItapecerica da Serra", "SP\tItapetininga", "SP\tItapeva", "SP\tItapevi", "SP\tItapira", "SP\tItapirapuã Paulista", "SP\tItápolis", "SP\tItaporanga", "SP\tItapuí", "SP\tItapura", "SP\tItaquaquecetuba", "SP\tItararé", "SP\tItariri", "SP\tItatiba", "SP\tItatinga", "SP\tItirapina", "SP\tItirapuã", "SP\tItobi", "SP\tItu", "SP\tItupeva", "SP\tItuverava", "SP\tJaborandi", "SP\tJaboticabal", "SP\tJacareí", "SP\tJaci", "SP\tJacupiranga", "SP\tJaguariúna", "SP\tJales", "SP\tJambeiro", "SP\tJandira", "SP\tJardinópolis", "SP\tJarinu", "SP\tJaú", "SP\tJeriquara", "SP\tJoanópolis", "SP\tJoão Ramalho", "SP\tJosé Bonifácio", "SP\tJúlio Mesquita", "SP\tJumirim", "SP\tJundiaí", "SP\tJunqueirópolis", "SP\tJuquiá", "SP\tJuquitiba", "SP\tLagoinha", "SP\tLaranjal Paulista", "SP\tLavínia", "SP\tLavrinhas", "SP\tLeme", "SP\tLençóis Paulista", "SP\tLimeira", "SP\tLindóia", "SP\tLins", "SP\tLorena", "SP\tLourdes", "SP\tLouveira", "SP\tLucélia", "SP\tLucianópolis", "SP\tLuís Antônio", "SP\tLuiziânia", "SP\tLupércio", "SP\tLutécia", "SP\tMacatuba", "SP\tMacaubal", "SP\tMacedônia", "SP\tMagda", "SP\tMairinque", "SP\tMairiporã", "SP\tManduri", "SP\tMarabá Paulista", "SP\tMaracaí", "SP\tMarapoama", "SP\tMariápolis", "SP\tMarília", "SP\tMarinópolis", "SP\tMartinópolis", "SP\tMatão", "SP\tMauá", "SP\tMendonça", "SP\tMeridiano", "SP\tMesópolis", "SP\tMiguelópolis", "SP\tMineiros do Tietê", "SP\tMiracatu", "SP\tMira Estrela", "SP\tMirandópolis", "SP\tMirante do Paranapanema", "SP\tMirassol", "SP\tMirassolândia", "SP\tMococa", "SP\tMoji Das Cruzes", "SP\tMogi Guaçu", "SP\tMoji-mirim", "SP\tMombuca", "SP\tMonções", "SP\tMongaguá", "SP\tMonte Alegre do Sul", "SP\tMonte Alto", "SP\tMonte Aprazível", "SP\tMonte Azul Paulista", "SP\tMonte Castelo", "SP\tMonteiro Lobato", "SP\tMonte Mor", "SP\tMorro Agudo", "SP\tMorungaba", "SP\tMotuca", "SP\tMurutinga do Sul", "SP\tNantes", "SP\tNarandiba", "SP\tNatividade da Serra", "SP\tNazaré Paulista", "SP\tNeves Paulista", "SP\tNhandeara", "SP\tNipoã", "SP\tNova Aliança", "SP\tNova Campina", "SP\tNova Canaã Paulista", "SP\tNova Castilho", "SP\tNova Europa", "SP\tNova Granada", "SP\tNova Guataporanga", "SP\tNova Independência", "SP\tNovais", "SP\tNova Luzitânia", "SP\tNova Odessa", "SP\tNovo Horizonte", "SP\tNuporanga", "SP\tOcauçu", "SP\tÓleo", "SP\tOlímpia", "SP\tOnda Verde", "SP\tOriente", "SP\tOrindiúva", "SP\tOrlândia", "SP\tOsasco", "SP\tOscar Bressane", "SP\tOsvaldo Cruz", "SP\tOurinhos", "SP\tOuroeste", "SP\tOuro Verde", "SP\tPacaembu", "SP\tPalestina", "SP\tPalmares Paulista", "SP\tPalmeira D´oeste", "SP\tPalmital", "SP\tPanorama", "SP\tParaguaçu Paulista", "SP\tParaibuna", "SP\tParaíso", "SP\tParanapanema", "SP\tParanapuã", "SP\tParapuã", "SP\tPardinho", "SP\tPariquera-açu", "SP\tParisi", "SP\tPatrocínio Paulista", "SP\tPaulicéia", "SP\tPaulínia", "SP\tPaulistânia", "SP\tPaulo de Faria", "SP\tPederneiras", "SP\tPedra Bela", "SP\tPedranópolis", "SP\tPedregulho", "SP\tPedreira", "SP\tPedrinhas Paulista", "SP\tPedro de Toledo", "SP\tPenápolis", "SP\tPereira Barreto", "SP\tPereiras", "SP\tPeruíbe", "SP\tPiacatu", "SP\tPiedade", "SP\tPilar do Sul", "SP\tPindamonhangaba", "SP\tPindorama", "SP\tPinhalzinho", "SP\tPiquerobi", "SP\tPiquete", "SP\tPiracaia", "SP\tPiracicaba", "SP\tPiraju", "SP\tPirajuí", "SP\tPirangi", "SP\tPirapora do Bom Jesus", "SP\tPirapozinho", "SP\tPirassununga", "SP\tPiratininga", "SP\tPitangueiras", "SP\tPlanalto", "SP\tPlatina", "SP\tPoá", "SP\tPoloni", "SP\tPompéia", "SP\tPongaí", "SP\tPontal", "SP\tPontalinda", "SP\tPontes Gestal", "SP\tPopulina", "SP\tPorangaba", "SP\tPorto Feliz", "SP\tPorto Ferreira", "SP\tPotim", "SP\tPotirendaba", "SP\tPracinha", "SP\tPradópolis", "SP\tPraia Grande", "SP\tPratânia", "SP\tPresidente Alves", "SP\tPresidente Bernardes", "SP\tPresidente Epitácio", "SP\tPresidente Prudente", "SP\tPresidente Venceslau", "SP\tPromissão", "SP\tQuadra", "SP\tQuatá", "SP\tQueiroz", "SP\tQueluz", "SP\tQuintana", "SP\tRafard", "SP\tRancharia", "SP\tRedenção da Serra", "SP\tRegente Feijó", "SP\tReginópolis", "SP\tRegistro", "SP\tRestinga", "SP\tRibeira", "SP\tRibeirão Bonito", "SP\tRibeirão Branco", "SP\tRibeirão Corrente", "SP\tRibeirão do Sul", "SP\tRibeirão Dos Índios", "SP\tRibeirão Grande", "SP\tRibeirão Pires", "SP\tRibeirão Preto", "SP\tRiversul", "SP\tRifaina", "SP\tRincão", "SP\tRinópolis", "SP\tRio Claro", "SP\tRio Das Pedras", "SP\tRio Grande da Serra", "SP\tRiolândia", "SP\tRosana", "SP\tRoseira", "SP\tRubiácea", "SP\tRubinéia", "SP\tSabino", "SP\tSagres", "SP\tSales", "SP\tSales Oliveira", "SP\tSalesópolis", "SP\tSalmourão", "SP\tSaltinho", "SP\tSalto", "SP\tSalto de Pirapora", "SP\tSalto Grande", "SP\tSandovalina", "SP\tSanta Adélia", "SP\tSanta Albertina", "SP\tSanta Bárbara D´oeste", "SP\tSanta Branca", "SP\tSanta Clara D´oeste", "SP\tSanta Cruz da Conceição", "SP\tSanta Cruz da Esperança", "SP\tSanta Cruz Das Palmeiras", "SP\tSanta Cruz do Rio Pardo", "SP\tSanta Ernestina", "SP\tSanta fé do Sul", "SP\tSanta Gertrudes", "SP\tSanta Isabel", "SP\tSanta Lúcia", "SP\tSanta Maria da Serra", "SP\tSanta Mercedes", "SP\tSantana da Ponte Pensa", "SP\tSantana de Parnaíba", "SP\tSanta Rita D´oeste", "SP\tSanta Rita do Passa Quatro", "SP\tSanta Rosa de Viterbo", "SP\tSanta Salete", "SP\tSanto Anastácio", "SP\tSanto André", "SP\tSanto Antônio da Alegria", "SP\tSanto Antônio de Posse", "SP\tSanto Antônio do Aracanguá", "SP\tSanto Antônio do Jardim", "SP\tSanto Antônio do Pinhal", "SP\tSanto Expedito", "SP\tSantópolis do Aguapeí", "SP\tSantos", "SP\tSão Bento do Sapucaí", "SP\tSão Bernardo do Campo", "SP\tSão Caetano do Sul", "SP\tSão Carlos", "SP\tSão Francisco", "SP\tSão João da Boa Vista", "SP\tSão João Das Duas Pontes", "SP\tSão João de Iracema", "SP\tSão João do Pau D´alho", "SP\tSão Joaquim da Barra", "SP\tSão José da Bela Vista", "SP\tSão José do Barreiro", "SP\tSão José do Rio Pardo", "SP\tSão José do Rio Preto", "SP\tSão José Dos Campos", "SP\tSão Lourenço da Serra", "SP\tSão Luís do Paraitinga", "SP\tSão Manuel", "SP\tSão Miguel Arcanjo", "SP\tSão Paulo", "SP\tSão Pedro", "SP\tSão Pedro do Turvo", "SP\tSão Roque", "SP\tSão Sebastião", "SP\tSão Sebastião da Grama", "SP\tSão Simão", "SP\tSão Vicente", "SP\tSarapuí", "SP\tSarutaiá", "SP\tSebastianópolis do Sul", "SP\tSerra Azul", "SP\tSerrana", "SP\tSerra Negra", "SP\tSertãozinho", "SP\tSete Barras", "SP\tSeverínia", "SP\tSilveiras", "SP\tSocorro", "SP\tSorocaba", "SP\tSud Mennucci", "SP\tSumaré", "SP\tSuzano", "SP\tSuzanápolis", "SP\tTabapuã", "SP\tTabatinga", "SP\tTaboão da Serra", "SP\tTaciba", "SP\tTaguaí", "SP\tTaiaçu", "SP\tTaiúva", "SP\tTambaú", "SP\tTanabi", "SP\tTapiraí", "SP\tTapiratiba", "SP\tTaquaral", "SP\tTaquaritinga", "SP\tTaquarituba", "SP\tTaquarivaí", "SP\tTarabai", "SP\tTarumã", "SP\tTatuí", "SP\tTaubaté", "SP\tTejupá", "SP\tTeodoro Sampaio", "SP\tTerra Roxa", "SP\tTietê", "SP\tTimburi", "SP\tTorre de Pedra", "SP\tTorrinha", "SP\tTrabiju", "SP\tTremembé", "SP\tTrês Fronteiras", "SP\tTuiuti", "SP\tTupã", "SP\tTupi Paulista", "SP\tTuriúba", "SP\tTurmalina", "SP\tUbarana", "SP\tUbatuba", "SP\tUbirajara", "SP\tUchoa", "SP\tUnião Paulista", "SP\tUrânia", "SP\tUru", "SP\tUrupês", "SP\tValentim Gentil", "SP\tValinhos", "SP\tValparaíso", "SP\tVargem", "SP\tVargem Grande do Sul", "SP\tVargem Grande Paulista", "SP\tVárzea Paulista", "SP\tVera Cruz", "SP\tVinhedo", "SP\tViradouro", "SP\tVista Alegre do Alto", "SP\tVitória Brasil", "SP\tVotorantim", "SP\tVotuporanga", "SP\tZacarias", "SP\tChavantes", "SP\tEstiva Gerbi" }));

        jLabel13.setText("Bairro");

        taDesc.setColumns(20);
        taDesc.setRows(5);
        jScrollPane2.setViewportView(taDesc);

        jLabel4.setText("Metragem");

        jLabel14.setText("Endereço");

        jLabel5.setText("Quartos");

        spSuites.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        jLabel6.setText("Banheiros");

        spQuartos.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel8.setText("Suites");

        spBanheiros.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel9.setText("Tipo de Imóvel");

        cbTp_imov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terrea", "Sobrado", "Condominio", "Duplex", "Flat", "Cobertura", "Kitnet", "Terreno-condominio", "Terreno-represa", " " }));

        jLabel10.setText("Tipo de Negócio");

        cbTp_Negocio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comprar", "Alugar" }));
        cbTp_Negocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTp_NegocioActionPerformed(evt);
            }
        });

        jLabel11.setText("Valor");

        jLabel12.setText("IPTU");

        jLabel15.setText("Titulo");

        jLabel16.setText("Cidade");

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tfCidade.setEnabled(false);

        tfTipoImovel.setEnabled(false);

        tfTipoNegocio.setEnabled(false);

        btLimpa.setText("Limpar");
        btLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAlterarLayout = new javax.swing.GroupLayout(pAlterar);
        pAlterar.setLayout(pAlterarLayout);
        pAlterarLayout.setHorizontalGroup(
            pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlterarLayout.createSequentialGroup()
                        .addComponent(tfTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205)
                        .addComponent(tfTipoNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pAlterarLayout.createSequentialGroup()
                            .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfMetragem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAlterarLayout.createSequentialGroup()
                            .addComponent(spQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spSuites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfBairro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAlterarLayout.createSequentialGroup()
                            .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAlterarLayout.createSequentialGroup()
                                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(tfCidade))
                                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAlterarLayout.createSequentialGroup()
                                        .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(148, 148, 148)
                                        .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cbTp_imov, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbTp_Negocio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfIptu)))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        pAlterarLayout.setVerticalGroup(
            pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMetragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spSuites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(spQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(spBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbTp_imov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbTp_Negocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTipoNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfIptu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(pAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpa)
                    .addComponent(btExcluir)
                    .addComponent(btAlterar))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        getContentPane().add(pAlterar);
        pAlterar.setBounds(10, 90, 800, 620);

        jLabel1.setText("Digite o titulo da propriedade:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 34, 180, 16);
        getContentPane().add(tfDadoPesquisa);
        tfDadoPesquisa.setBounds(6, 55, 173, 22);

        btPesquisa.setText("...");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisa);
        btPesquisa.setBounds(185, 55, 31, 23);

        tfID.setEnabled(false);
        getContentPane().add(tfID);
        tfID.setBounds(720, 410, 64, 22);

        btVoltar.setBackground(new java.awt.Color(255, 51, 51));
        btVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVoltar.setForeground(new java.awt.Color(242, 242, 242));
        btVoltar.setText("X");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(830, 10, 49, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
        Desconectar();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void cbTp_NegocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTp_NegocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTp_NegocioActionPerformed

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        String sql, titulo;
        
        titulo = "%" + tfDadoPesquisa.getText() + "%";
        
        try{
            sql = "select id, titulo, descricao from imovel where titulo like ?";
            PreparedStatement stm = con.prepareStatement(sql, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            stm.setString(1, titulo);
            ResultSet rs = stm.executeQuery();
            
            if(rs.first()){
                pTabela.setVisible(true);
                String[] linha = new String[]{rs.getString("id"), rs.getString("titulo"), rs.getString("descricao")};
                imoveis.addRow(linha);
                while(rs.next()){
                    linha = new String[]{rs.getString("id"), rs.getString("titulo"), rs.getString("descricao")};
                    imoveis.addRow(linha);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possivel encontrar o imovel!");
            }
        } catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Erro ao encontrar os dados! " + erro);
        }
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void btSairTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairTabelaActionPerformed
        pTabela.setVisible(false);
        limparTabela();
    }//GEN-LAST:event_btSairTabelaActionPerformed

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        String id, sql, idSubcat, tpNegocio;
        int linha;
        linha = jTable1.getSelectedRow();
        id = (String) jTable1.getValueAt(linha, 0);
        tfID.setText(id);
        sql = "select * from imovel where id = ?";
        //Aqui começa a rotina de consultas
        try{ 
            PreparedStatement stm = con.prepareStatement(sql, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            stm.setString(1, id);
            ResultSet rs = stm.executeQuery();
            
            if(rs.first()){
                //Mostra os dados na parte de alterar
                tfTitulo.setText(rs.getString("titulo"));
                taDesc.setText(rs.getString("descricao"));
                tfMetragem.setText(rs.getString("metragem"));
                tfValor.setText(rs.getString("valor"));
                tfIptu.setText(rs.getString("IPTU"));
                tfBairro.setText(rs.getString("bairro"));
                tfEndereco.setText(rs.getString("endereco"));
                spBanheiros.setValue(Integer.parseInt(rs.getString("banheiros")));
                spSuites.setValue(Integer.parseInt(rs.getString("suites")));
                spQuartos.setValue(Integer.parseInt(rs.getString("quartos")));
                tfTipoNegocio.setText(rs.getString("tipo_negocio"));
                tfCidade.setText(rs.getString("cidade"));
                
                idSubcat = rs.getString("id_tipo_imovel_subcategorias");
                
                //Segunda consulta da rotina, serve para pegar o tipo de imovel
                PreparedStatement stm1 = con.prepareStatement("select subcategoria from tipo_imovel_subcategoria where id = ?",ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                stm1.setString(1, idSubcat);
                ResultSet rs1 = stm1.executeQuery();
                if(rs1.first()){
                    tfTipoImovel.setText(rs1.getString("subcategoria"));
                }
            }
            
        } catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Erro ao encontrar os dados!" + erro);
        }
        
        
    }//GEN-LAST:event_btSelecionarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        String sqlConsulta, sqlAlterar, titulo, desc, metragem, quartos, suites, banheiros, tpImovel, tpNegocio, valor, iptu, cidade, bairro, endereco, idSubcategoria = null, id;
        int result, opcao;
        
        titulo = tfTitulo.getText();
        desc = taDesc.getText();
        metragem = tfMetragem.getText();
        quartos = spQuartos.getValue().toString();
        suites = spSuites.getValue().toString();
        banheiros = spBanheiros.getValue().toString();
        tpNegocio = cbTp_Negocio.getSelectedItem().toString();
        valor = tfValor.getText();
        iptu = tfIptu.getText();
        cidade = cbCidade.getSelectedItem().toString();
        bairro = tfBairro.getText();
        endereco = tfEndereco.getText();
        id = tfID.getText();
        
        tpImovel = "%" + cbTp_imov.getSelectedItem().toString() + "%";
        
        try{
            sqlConsulta = "Select id from tipo_imovel_subcategoria where subcategoria like ?";
            PreparedStatement stm = con.prepareStatement(sqlConsulta, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            stm.setString(1, tpImovel);
            ResultSet rs = stm.executeQuery();
            if(rs.first()){
                idSubcategoria = rs.getString("id");
            } else {
                JOptionPane.showMessageDialog(null, "Esse tipo de imovel não existe!");
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "erro" + e);
        }
        
        try{
            sqlAlterar = "Update imovel set titulo=?, descricao=?, metragem=?, quartos=?, suites=?, banheiros=?, id_tipo_imovel_subcategorias=?, tipo_negocio=?, valor=?, IPTU=?, cidade=?, bairro=?, endereco=? where id = ?";
            PreparedStatement stm = con.prepareStatement(sqlAlterar);
            stm.setString(1, titulo);
            stm.setString(2, desc);
            stm.setString(3, metragem);
            stm.setString(4, quartos);
            stm.setString(5, suites);
            stm.setString(6, banheiros);
            stm.setString(8, idSubcategoria);
            stm.setString(9, tpNegocio);
            stm.setString(10, valor);
            stm.setString(11, iptu);
            stm.setString(12, cidade);
            stm.setString(13, bairro);
            stm.setString(14, endereco);
            stm.setString(15, id);
            Object[] options = {"Sim", "Não"};
            opcao = JOptionPane.showOptionDialog(null, "Confirmar alteração?", "Alteração", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            
            if(opcao == 0){
                result = stm.executeUpdate();
                if(result > 0){
                    JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao alterar!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Alteração cancelada!");
            }
            
        } catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "erro" + erro);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        //realiza a exclusão do imovel, ainda é preciso realizar a exclusão das imagens
        String sql, id;
        int opcao;
        
        id = tfID.getText();
        
        sql = "delete from imovel where id = ?";
        
        try{
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1, id);
            Object[] options = {"Sim", "Não"};
            opcao = JOptionPane.showOptionDialog(null, "Deseja mesmo realizar essa exclusão?", "Excluie", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if(opcao == 0){
                boolean resultado = stm.execute();
                if(resultado == false){
                    JOptionPane.showMessageDialog(null, "Dados excluidos com sucesso!");
                    limparCampos();
                } else{
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada!");
            }
        } catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Hove um erro ao excluir os dados! "+erro);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpaActionPerformed
        limparCampos();
        
    }//GEN-LAST:event_btLimpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpa;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JButton btSairTabela;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbCidade;
    private javax.swing.JComboBox<String> cbTp_Negocio;
    private javax.swing.JComboBox<String> cbTp_imov;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pAlterar;
    private javax.swing.JPanel pTabela;
    private javax.swing.JSpinner spBanheiros;
    private javax.swing.JSpinner spQuartos;
    private javax.swing.JSpinner spSuites;
    private javax.swing.JTextArea taDesc;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfDadoPesquisa;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfIptu;
    private javax.swing.JTextField tfMetragem;
    private javax.swing.JTextField tfTipoImovel;
    private javax.swing.JTextField tfTipoNegocio;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
